// بيانات الفئات
export const categories = [
  { id: 'anxiety', name: 'القلق والتوتر', color: '#9EBF3B' },
  { id: 'depression', name: 'الاكتئاب', color: '#D6A29A' },
  { id: 'relationships', name: 'العلاقات', color: '#9EBF3B' },
  { id: 'self-development', name: 'التنمية الذاتية', color: '#D6A29A' },
  { id: 'parenting', name: 'تربية الأطفال', color: '#9EBF3B' },
  { id: 'trauma', name: 'الصدمات', color: '#D6A29A' },
  { id: 'addiction', name: 'الإدمان', color: '#9EBF3B' },
  { id: 'work-stress', name: 'ضغوط العمل', color: '#D6A29A' }
]

// بيانات المكتبة مع روابط صور من الإنترنت
export const libraryData = [
  {
    id: 1,
    title: 'دليل التعامل مع القلق النفسي',
    description: 'دليل شامل لفهم القلق النفسي وأساليب التعامل معه بشكل عملي وفعال',
    author: 'د. أحمد محمد',
    type: 'book',
    category: 'anxiety',
    coverImage: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=500&fit=crop',
    publishDate: '2024-01-15',
    downloads: 1247,
    views: 3568,
    fileSize: '2.4 MB',
    pages: 156,
    isNew: true,
    rating: 4.8
  },
  {
    id: 2,
    title: 'الاكتئاب: الأسباب والعلاج',
    description: 'بحث علمي متعمق حول أسباب الاكتئاب وأحدث طرق العلاج النفسي والدوائي',
    author: 'د. سارة العلي',
    type: 'research',
    category: 'depression',
    coverImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&h=500&fit=crop',
    publishDate: '2024-02-20',
    downloads: 892,
    views: 2145,
    fileSize: '1.8 MB',
    pages: 89,
    isNew: false,
    rating: 4.6
  },
  {
    id: 3,
    title: 'فن التواصل في العلاقات',
    description: 'تعلم مهارات التواصل الفعال لبناء علاقات صحية ومستدامة',
    author: 'د. خالد عبدالله',
    type: 'guide',
    category: 'relationships',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=500&fit=crop',
    publishDate: '2024-01-08',
    downloads: 1563,
    views: 3987,
    fileSize: '3.1 MB',
    pages: 234,
    isNew: true,
    rating: 4.9
  },
  {
    id: 4,
    title: 'التنمية الذاتية والثقة بالنفس',
    description: 'استراتيجيات عملية لتعزيز الثقة بالنفس وتحقيق النمو الشخصي',
    author: 'د. فاطمة ناصر',
    type: 'book',
    category: 'self-development',
    coverImage: 'https://images.unsplash.com/photo-1491309055486-24ae511c15c7?w=400&h=500&fit=crop',
    publishDate: '2023-12-10',
    downloads: 2105,
    views: 5123,
    fileSize: '2.7 MB',
    pages: 189,
    isNew: false,
    rating: 4.7
  },
  {
    id: 5,
    title: 'تربية الأطفال في العصر الحديث',
    description: 'أحدث الأساليب العلمية في تربية الأطفال وتعزيز صحتهم النفسية',
    author: 'د. محمد السعدون',
    type: 'article',
    category: 'parenting',
    coverImage: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400&h=500&fit=crop',
    publishDate: '2024-03-05',
    downloads: 745,
    views: 1876,
    fileSize: '1.2 MB',
    pages: 45,
    isNew: true,
    rating: 4.5
  },
  {
    id: 6,
    title: 'التعافي من الصدمات النفسية',
    description: 'رحلة الشفاء من الصدمات النفسية واستعادة التوازن الداخلي',
    author: 'د. ليلى القحطاني',
    type: 'book',
    category: 'trauma',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    publishDate: '2024-02-28',
    downloads: 983,
    views: 2456,
    fileSize: '2.9 MB',
    pages: 201,
    isNew: false,
    rating: 4.8
  },
  {
    id: 7,
    title: 'برنامج التعافي من الإدمان',
    description: 'دليل عملي مكون من 12 خطوة للتعافي من مختلف أنواع الإدمان',
    author: 'د. وليد الشمري',
    type: 'guide',
    category: 'addiction',
    coverImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=500&fit=crop',
    publishDate: '2024-01-22',
    downloads: 1124,
    views: 2987,
    fileSize: '2.1 MB',
    pages: 134,
    isNew: true,
    rating: 4.6
  },
  {
    id: 8,
    title: 'إدارة ضغوط العمل',
    description: 'استراتيجيات فعالة للتعامل مع ضغوط العمل والحفاظ على الصحة النفسية',
    author: 'د. نورة الرشيد',
    type: 'article',
    category: 'work-stress',
    coverImage: 'https://images.unsplash.com/photo-1521791055366-0d553872125f?w=400&h=500&fit=crop',
    publishDate: '2024-03-12',
    downloads: 867,
    views: 2134,
    fileSize: '1.5 MB',
    pages: 67,
    isNew: true,
    rating: 4.4
  },
  {
    id: 9,
    title: 'العلاج المعرفي السلوكي',
    description: 'دليل شامل لفهم وتطبيق تقنيات العلاج المعرفي السلوكي',
    author: 'د. عبدالرحمن الغامدي',
    type: 'book',
    category: 'anxiety',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    publishDate: '2023-11-30',
    downloads: 1789,
    views: 4231,
    fileSize: '3.4 MB',
    pages: 278,
    isNew: false,
    rating: 4.9
  },
  {
    id: 10,
    title: 'الصحة النفسية للمراهقين',
    description: 'بحث ميداني حول تحديات الصحة النفسية لدى المراهقين وطرق الدعم',
    author: 'د. هدى العتيبي',
    type: 'research',
    category: 'depression',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=500&fit=crop',
    publishDate: '2024-02-14',
    downloads: 654,
    views: 1678,
    fileSize: '1.9 MB',
    pages: 92,
    isNew: false,
    rating: 4.3
  },
  {
    id: 11,
    title: 'التأمل والوعي الذاتي',
    description: 'تمارين عملية للتأمل وتطوير الوعي الذاتي لتحسين الصحة النفسية',
    author: 'د. بدر الحربي',
    type: 'guide',
    category: 'self-development',
    coverImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=500&fit=crop',
    publishDate: '2024-03-01',
    downloads: 1342,
    views: 3256,
    fileSize: '2.3 MB',
    pages: 156,
    isNew: true,
    rating: 4.7
  },
  {
    id: 12,
    title: 'العلاج الأسري المتكامل',
    description: 'أساليب مبتكرة في العلاج الأسري لتحسين ديناميكيات العلاقات',
    author: 'د. منى الفهد',
    type: 'book',
    category: 'relationships',
    coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=500&fit=crop',
    publishDate: '2024-01-05',
    downloads: 987,
    views: 2456,
    fileSize: '2.8 MB',
    pages: 198,
    isNew: false,
    rating: 4.6
  }
]

// إحصائيات المكتبة
export const libraryStats = {
  totalItems: libraryData.length,
  books: libraryData.filter(item => item.type === 'book').length,
  articles: libraryData.filter(item => item.type === 'article').length,
  guides: libraryData.filter(item => item.type === 'guide').length,
  research: libraryData.filter(item => item.type === 'research').length,
  downloads: libraryData.reduce((total, item) => total + item.downloads, 0),
  views: libraryData.reduce((total, item) => total + item.views, 0)
}